-- AlterTable
ALTER TABLE `empresas`
  ADD COLUMN `razaoSocial` VARCHAR(191) NULL,
  ADD COLUMN `cnpj` VARCHAR(191) NULL,
  ADD COLUMN `inscricaoEstadual` VARCHAR(191) NULL,
  ADD COLUMN `inscricaoMunicipal` VARCHAR(191) NULL,
  ADD COLUMN `dataFundacao` DATETIME(3) NULL,
  ADD COLUMN `tipoEmpresa` ENUM('RESTAURANTE', 'LANCHONETE', 'PIZZARIA', 'HAMBURGUERIA', 'CAFETERIA', 'ACAITERIA', 'PADARIA', 'SORVETERIA', 'FOOD_TRUCK', 'DOCERIA', 'MARMITARIA', 'OUTRO') NULL DEFAULT 'OUTRO',
  ADD COLUMN `regimeTributario` VARCHAR(191) NULL,
  ADD COLUMN `ramoAtividade` VARCHAR(191) NULL,
  ADD COLUMN `descricao` TEXT NULL,
  ADD COLUMN `cep` VARCHAR(191) NULL,
  ADD COLUMN `endereco` VARCHAR(191) NULL,
  ADD COLUMN `numero` VARCHAR(191) NULL,
  ADD COLUMN `complemento` VARCHAR(191) NULL,
  ADD COLUMN `bairro` VARCHAR(191) NULL,
  ADD COLUMN `cidade` VARCHAR(191) NULL,
  ADD COLUMN `estado` VARCHAR(191) NULL,
  ADD COLUMN `pais` VARCHAR(191) NULL DEFAULT 'Brasil',
  ADD COLUMN `telefone` VARCHAR(191) NULL,
  ADD COLUMN `whatsapp` VARCHAR(191) NULL,
  ADD COLUMN `emailContato` VARCHAR(191) NULL,
  ADD COLUMN `site` VARCHAR(191) NULL,
  ADD COLUMN `instagram` VARCHAR(191) NULL,
  ADD COLUMN `facebook` VARCHAR(191) NULL,
  ADD COLUMN `tiktok` VARCHAR(191) NULL,
  ADD COLUMN `youtube` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `usuarios`
  ADD COLUMN `cpf` VARCHAR(191) NULL,
  ADD COLUMN `rg` VARCHAR(191) NULL,
  ADD COLUMN `dataNascimento` DATETIME(3) NULL,
  ADD COLUMN `telefone` VARCHAR(191) NULL,
  ADD COLUMN `fotoUrl` VARCHAR(191) NULL;

-- CreateIndex
CREATE UNIQUE INDEX `empresas_cnpj_key` ON `empresas`(`cnpj`);

-- CreateIndex
CREATE UNIQUE INDEX `usuarios_cpf_key` ON `usuarios`(`cpf`);
