-- AlterTable
ALTER TABLE `impressoras` MODIFY `setor` ENUM('COZINHA', 'BAR', 'CONFEITARIA', 'PIZZARIA', 'ACAI', 'SALGADOS', 'BALCAO', 'GARCOM', 'CAIXA', 'DELIVERY', 'OUTRO') NOT NULL DEFAULT 'COZINHA';

-- AlterTable
ALTER TABLE `print_jobs` MODIFY `setor` ENUM('COZINHA', 'BAR', 'CONFEITARIA', 'PIZZARIA', 'ACAI', 'SALGADOS', 'BALCAO', 'GARCOM', 'CAIXA', 'DELIVERY', 'OUTRO') NOT NULL;

-- AlterTable
ALTER TABLE `produtos` MODIFY `setorProducao` ENUM('COZINHA', 'BAR', 'CONFEITARIA', 'PIZZARIA', 'ACAI', 'SALGADOS', 'BALCAO', 'GARCOM', 'CAIXA', 'DELIVERY', 'OUTRO') NOT NULL DEFAULT 'COZINHA';

