-- AlterTable
ALTER TABLE `pedido_itens` ADD COLUMN `setorProducao` ENUM('COZINHA', 'BAR', 'CONFEITARIA', 'PIZZARIA', 'ACAI', 'SALGADOS', 'BALCAO', 'GARCOM', 'CAIXA', 'DELIVERY', 'OUTRO') NOT NULL DEFAULT 'COZINHA';

